# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - resumevisitor-fn

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Set up Python version'
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: 'Install dependencies into a local folder'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt #For testing environment
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Test with unittest
        run: |
          python -m unittest test.py -v

      - name: 'Deploy to Azure Functions'
        id: deploy-to-webapp
        uses: Azure/functions-action@v1
        with:
          app-name: 'resumevisitor-fn'
          slot-name: 'Production'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E36E98A6015F480EA3745B2541890F8C }}
